# Generated by Django 3.2.8 on 2022-05-25 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_order_orderitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
