# Generated by Django 3.2.8 on 2022-06-13 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_shippingaddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
